# Generated by Django 5.2.3 on 2025-07-06 12:50

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='aura',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(blank=True, choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('fullstack', 'Fullstack'), ('designer', 'Designer'), ('data', 'Data'), ('devops', 'DevOps')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('open', 'Open to Work'), ('busy', 'Busy'), ('living', 'Living Life 😎')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.language'),
        ),
    ]
