# Generated by Django 5.2.3 on 2025-07-02 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('availability', models.CharField(choices=[('active', 'Activa'), ('paused', 'En Pausa'), ('finished', 'Terminado')], default='active', max_length=10)),
                ('active_state', models.CharField(blank=True, choices=[('review', 'En revisión'), ('searching', 'Buscando miembros'), ('development', 'Solo desarrollo')], max_length=20, null=True)),
                ('privacy', models.CharField(choices=[('public', 'Pública'), ('private', 'Privada'), ('friends', 'Solo Amigos')], default='public', max_length=10)),
                ('links', models.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_authored', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='projects_joined', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, to='users.skill')),
            ],
        ),
    ]
