# Generated by Django 5.2.3 on 2025-07-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active_state',
            field=models.CharField(blank=True, choices=[('review', 'Reviewing'), ('searching', 'Hiring'), ('development', 'Only develop')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='availability',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Only Friends')], default='public', max_length=10),
        ),
    ]
